name: flake8

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]


jobs:
  flake8:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.10.6]
      steps:
          - uses: actions/checkout@v2
          - name: Install python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install deps
            run: |
              python -m pip install --upgrade pip
              pip install flake8
          - name: Run flake8
            run: flake8 .

  deploy:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    needs: flake8
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          folder: ${{ secrets.FOLDER }}
          deploy: ${{ secrets.DEPLOY_NAME }}
          script: |
            cd silver_unicorn
            ./deploy.sh
